### ISSUE TITLE
copy word or copy other things does not work

### ISSUE THREAD

**Issue by LuoPX-15510486969** [manateelazycat/thing-edit#2]
setq: Symbol’s value as variable is void: compilation-highlight-overlay

![onekey](https://user-images.githubusercontent.com/13256245/50401297-7a67fe00-07c8-11e9-84f4-0d46a3ed6aa0.gif)

**Comment by manateelazycat** [comment]
Fix by https://github.com/manateelazycat/thing-edit/commit/0e3089ca1b9cbbb0798ea5e671df24172ddc7770
