### ISSUE TITLE
Wrong type argument: commandp, comment-copy

### ISSUE THREAD

**Issue by ctrl2wei** [manateelazycat/thing-edit#3]
When use **thing-copy-comment**, emacs can not find function **comment-copy**.

https://github.com/manateelazycat/thing-edit/blob/89922e6e89ee36b85f59b81a2c81e4c6511d7695/thing-edit.el#L557

 It turned out that it came from another file which belongs to your personal emacs config file.

https://github.com/manateelazycat/lazycat-emacs/blob/5962428df64ad7835df8aa6b4bc97f073368ced0/site-lisp/extensions/lazycat/basic-toolkit.el#L236-L252

**Comment by manateelazycat** [comment]
done https://github.com/manateelazycat/thing-edit/commit/5e801753601961ff4f2a79ad31f15583ee36fc06
