### ISSUE TITLE
thing-replace-region-or-line cannot get correct region bound

### ISSUE THREAD

**Issue by lyjdwh** [manateelazycat/thing-edit#6]
When using `thing-replace-region-or-line` to replace a region, it returns error  " No regions here".

`thing-replace-region-or-line` uses `(bounds-of-thing-at-point 'region)` to get region bound, but it return nil.

**Comment by manateelazycat** [comment]
Fix by https://github.com/manateelazycat/thing-edit/commit/117eadcc43f6933e14b77c20b7983ee234cba794
